### ISSUE TITLE
Check for plain value in `auditMap`

### ISSUE THREAD

**Issue by martingronlund** [nxtedition/nxt-lib#14]
Not a serious problem, but in case a user ever does

```js
auditMap(x => {
  if (!x) {
    return
  }
  return apiCall(x) // some Promise or Observable
})
```

we should probably use https://rxjs-dev.firebaseapp.com/api/index/function/isObservable
over here https://github.com/nxtedition/nxt-lib/blob/master/src/rxjs/auditMap.js#L36

**Comment by martingronlund** [comment]
or maybe it's better to just throw - I'm not sure

let's not 🚲 🏠

**Comment by ronag** [comment]
The way it works with all other rxjs operators is to throw. I think we want to keep it consistent.
